config/routes.rb
FrontendExercise::Application.routes.draw do
  resources :homepage, :only => [:index]
  resources :profiles

  root :to => 'profiles#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :profile

  attr_accessible :city, :country, :state, :street, :zip

  validates_presence_of :street, :city, :state, :zip, :country
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  respond_to :html

  expose(:profile)
  expose(:profiles) { Profile.all }

  def show
    respond_with profile
  end

  def index
    respond_with profiles
  end

  def create
    new_profile = Profile.new profile_params
    if new_profile.save
      redirect_to profile_path(new_profile.id)
    else
      respond_with new_profile
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :email, :gender, :income, :date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FrontendExercise
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application", :jquery
    = csrf_meta_tags
  %body
    = yield

app/views/profiles/_profile.html.haml
%tr
  %td
    = profile.first_name
  %td
    = profile.last_name
  %td
    = profile.email
  %td
    = profile.gender
  %td
    = profile.income
  %td
    = profile.date_of_birth
  - if profile.location
    %td
      = profile.location.street
    %td
      = profile.location.city
    %td
      = profile.location.state
    %td
      = profile.location.zip
    %td
      = profile.location.country
  %td
    = profile.created_at

app/views/profiles/_profile_header.html.haml
%thead
  %tr
    %th
      First Name
    %th
      Last Name
    %th
      Email
    %th
      Gender
    %th
      Income
    %th
      Date of Birth
    %th
      Street
    %th
      City
    %th
      State
    %th
      Zip
    %th
      Country
    %th
      Profile Created

app/views/profiles/index.html.haml
.profileIndex
  %h3 Profiles List
  %table
    = render :partial => 'profiles/profile_header'
    %tbody
      = render :partial => 'profiles/profile', :collection => profiles
  %br
  = link_to 'create a profile', new_profile_path

app/views/profiles/new.html.haml
.createProfile
  %h2 Please Register
  
  = form_for profile, :url => profiles_path, :method => :post do |f|

    .topinput
      = f.text_field 'first_name', :placeholder => "First Name"
      = f.text_field 'last_name', :placeholder => "Last Name"

    %br
    .emailinput
      = f.text_field 'email', :placeholder => "Email"

    %br
    .genderinput
      = label :profiles, :gender, 'Male'
      = f.radio_button 'gender', 'm'
      = label :profiles, :gender, 'Female'
      = f.radio_button 'gender', 'f'
  
    .clear
    
    %br
    = label :profiles, :date_of_birth, 'Birthday'
    .birthDay
      = f.date_select :date_of_birth

    %br
    %h3 Annual Income
    = label :profiles, :income, '< $1'
    = f.radio_button 'income', '1'

    = label :profiles, :income, 'About $1'
    = f.radio_button 'income', '2'

    = label :profiles, :income, '> $1'
    = f.radio_button 'income', '3'

    %br
    = f.submit 'Submit'

  %br
  %br
  = link_to 'what this should look like..', '/form.jpg', :target => '_blank'

app/views/profiles/show.html.haml
.profileDetails
  %h3 Profile details for #{@profile.first_name} #{@profile.last_name}.
  %table
    = render :partial => 'profile_header'
    %tbody
      = render :partial => 'profile', :locals => {:profile => @profile}

  %br
  = link_to 'Back to profiles list', profiles_path